spring.application.name=flowShop

# ? MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3307/SpringFlowerDB
spring.datasource.username=root
spring.datasource.password=Raksa123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ? JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port
server.port=8080

management.endpoints.web.exposure.include=mappings
file.upload-dir=D:/uploads/images
spring.security.user.name=admin
spring.security.user.password=123456

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#mail sender

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lik248893@gmail.com
spring.mail.password=nrehcsjzwaqrxikw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.default-encoding=UTF-8

# Logging Configuration
logging.level.com.flowShop.spring.filter=INFO